"""initial schema

Revision ID: 35ce2faabf86
Revises: 
Create Date: 2026-05-31 19:07:52.719793
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = '35ce2faabf86'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_attempts',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('routing_decision_id', sa.String(), nullable=True),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_attempts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_attempts_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_attempts_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index('ix_attempt_task_status', ['task_id', 'status'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_trace_id'), ['trace_id'], unique=False)

    op.create_table('command_runs',
    sa.Column('attempt_id', sa.String(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('command_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_command_runs_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_command_runs_trace_id'), ['trace_id'], unique=False)

    op.create_table('context_items',
    sa.Column('pack_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_items_pack_id'), ['pack_id'], unique=False)

    op.create_table('context_packs',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_packs_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_packs_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_packs_task_id'), ['task_id'], unique=False)

    op.create_table('diff_bundles',
    sa.Column('attempt_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diff_bundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diff_bundles_attempt_id'), ['attempt_id'], unique=False)

    op.create_table('evaluation_results',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('attempt_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_results_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_results_task_id'), ['task_id'], unique=False)

    op.create_table('evidence',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('attempt_id', sa.String(), nullable=True),
    sa.Column('verification_run_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_verification_run_id'), ['verification_run_id'], unique=False)

    op.create_table('human_labels',
    sa.Column('review_item_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('human_labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_human_labels_review_item_id'), ['review_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_human_labels_task_id'), ['task_id'], unique=False)

    op.create_table('human_review_items',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('human_review_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_human_review_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_human_review_items_task_id'), ['task_id'], unique=False)

    op.create_table('policy_versions',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_versions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_versions_status'), ['status'], unique=False)

    op.create_table('post_merge_outcomes',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('attempt_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_merge_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_merge_outcomes_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_merge_outcomes_task_id'), ['task_id'], unique=False)

    op.create_table('repo_snapshots',
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repo_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repo_snapshots_repo_id'), ['repo_id'], unique=False)

    op.create_table('repositories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_events',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('attempt_id', sa.String(), nullable=True),
    sa.Column('routing_decision_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reward_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reward_events_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_events_routing_decision_id'), ['routing_decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_events_task_id'), ['task_id'], unique=False)

    op.create_table('routing_decisions',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routing_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routing_decisions_policy_version'), ['policy_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_routing_decisions_task_id'), ['task_id'], unique=False)

    op.create_table('tasks',
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('tool_calls',
    sa.Column('attempt_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_calls_attempt_id'), ['attempt_id'], unique=False)

    op.create_table('verification_plans',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_plans_task_id'), ['task_id'], unique=False)

    op.create_table('verification_runs',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('attempt_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_runs_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_runs_task_id'), ['task_id'], unique=False)

    op.create_table('weak_labels',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('attempt_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weak_labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weak_labels_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weak_labels_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weak_labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weak_labels_task_id'))
        batch_op.drop_index(batch_op.f('ix_weak_labels_attempt_id'))

    op.drop_table('weak_labels')
    with op.batch_alter_table('verification_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_runs_task_id'))
        batch_op.drop_index(batch_op.f('ix_verification_runs_attempt_id'))

    op.drop_table('verification_runs')
    with op.batch_alter_table('verification_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_plans_task_id'))

    op.drop_table('verification_plans')
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_calls_attempt_id'))

    op.drop_table('tool_calls')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_repo_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('routing_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routing_decisions_task_id'))
        batch_op.drop_index(batch_op.f('ix_routing_decisions_policy_version'))

    op.drop_table('routing_decisions')
    with op.batch_alter_table('reward_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_events_task_id'))
        batch_op.drop_index(batch_op.f('ix_reward_events_routing_decision_id'))
        batch_op.drop_index(batch_op.f('ix_reward_events_attempt_id'))

    op.drop_table('reward_events')
    op.drop_table('repositories')
    with op.batch_alter_table('repo_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repo_snapshots_repo_id'))

    op.drop_table('repo_snapshots')
    with op.batch_alter_table('post_merge_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_merge_outcomes_task_id'))
        batch_op.drop_index(batch_op.f('ix_post_merge_outcomes_attempt_id'))

    op.drop_table('post_merge_outcomes')
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_versions_status'))
        batch_op.drop_index(batch_op.f('ix_policy_versions_name'))

    op.drop_table('policy_versions')
    with op.batch_alter_table('human_review_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_review_items_task_id'))
        batch_op.drop_index(batch_op.f('ix_human_review_items_status'))

    op.drop_table('human_review_items')
    with op.batch_alter_table('human_labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_labels_task_id'))
        batch_op.drop_index(batch_op.f('ix_human_labels_review_item_id'))

    op.drop_table('human_labels')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_verification_run_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_task_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_attempt_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_results_task_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_results_attempt_id'))

    op.drop_table('evaluation_results')
    with op.batch_alter_table('diff_bundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diff_bundles_attempt_id'))

    op.drop_table('diff_bundles')
    with op.batch_alter_table('context_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_packs_task_id'))
        batch_op.drop_index(batch_op.f('ix_context_packs_repo_id'))
        batch_op.drop_index(batch_op.f('ix_context_packs_content_hash'))

    op.drop_table('context_packs')
    with op.batch_alter_table('context_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_items_pack_id'))

    op.drop_table('context_items')
    with op.batch_alter_table('command_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_command_runs_trace_id'))
        batch_op.drop_index(batch_op.f('ix_command_runs_attempt_id'))

    op.drop_table('command_runs')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_trace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_event_type'))

    op.drop_table('audit_log')
    op.drop_table('artifacts')
    with op.batch_alter_table('agent_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_attempt_task_status')
        batch_op.drop_index(batch_op.f('ix_agent_attempts_trace_id'))
        batch_op.drop_index(batch_op.f('ix_agent_attempts_task_id'))
        batch_op.drop_index(batch_op.f('ix_agent_attempts_status'))

    op.drop_table('agent_attempts')
    # ### end Alembic commands ###
