"""add run_states

Revision ID: 7d851647083c
Revises: 35ce2faabf86
Create Date: 2026-05-31 21:54:32.823499
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401


revision: str = '7d851647083c'
down_revision: str | None = '35ce2faabf86'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_states',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_states_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_states_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_states_trace_id'), ['trace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_states_trace_id'))
        batch_op.drop_index(batch_op.f('ix_run_states_task_id'))
        batch_op.drop_index(batch_op.f('ix_run_states_status'))

    op.drop_table('run_states')
    # ### end Alembic commands ###
