"""add agent_traces

Revision ID: c85110947d6c
Revises: e36e7a55308e
Create Date: 2026-06-01 09:36:08.913255
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401


revision: str = 'c85110947d6c'
down_revision: str | None = 'e36e7a55308e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_traces',
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('adapter_name', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_traces_adapter_name'), ['adapter_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_traces_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_traces_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_traces_task_id'))
        batch_op.drop_index(batch_op.f('ix_agent_traces_attempt_id'))
        batch_op.drop_index(batch_op.f('ix_agent_traces_adapter_name'))

    op.drop_table('agent_traces')
    # ### end Alembic commands ###
