"""add policy_states

Revision ID: e36e7a55308e
Revises: 49a4137ad650
Create Date: 2026-06-01 06:17:33.586562
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401


revision: str = 'e36e7a55308e'
down_revision: str | None = '49a4137ad650'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_states',
    sa.Column('policy_version', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_states_policy_version'), ['policy_version'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_states_policy_version'))

    op.drop_table('policy_states')
    # ### end Alembic commands ###
