"""Guarded PR pipeline (Alpha 32): draft patch -> draft PR on a sandbox branch.

The next rung above ``draft_patch``: take a verified draft and build a DRAFT PR — apply it to
a NEW feature branch in the sandbox repo, commit, generate a PR description, and produce a
rollback plan. Hard write-safety invariants:

- the patch is committed to a fresh ``acp/draft-*`` feature branch, NEVER a protected branch
  (main/master/production/release);
- applying requires the draft to have been VERIFIED in the sandbox;
- merging into a protected branch is NOT performed here — it requires human approval
  (``draft_pr`` only goes as far as the branch + PR description);
- every draft PR carries a rollback plan (delete branch / reset to base).
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass, field
from pathlib import Path

PROTECTED_BRANCHES = frozenset({"main", "master", "production", "release"})


def safe_branch_name(task_id: str) -> str:
    slug = "".join(c if c.isalnum() or c in "-_" else "-" for c in task_id)[:40]
    return f"acp/draft-{slug}"


@dataclass
class RollbackPlan:
    branch: str
    base_commit: str
    delete_branch_cmd: str
    reset_cmd: str

    def to_dict(self) -> dict:
        return dict(self.__dict__)


@dataclass
class DraftPR:
    task_id: str
    branch: str
    applied_to_branch: bool
    targeted_protected_branch: bool      # INVARIANT: must be False
    verified: bool
    base_commit: str
    head_commit: str | None
    description: str
    rollback: dict | None = None
    blocked_reason: str | None = None

    def to_dict(self) -> dict:
        return dict(self.__dict__)


def _git(repo: Path, *args: str) -> str:
    return subprocess.run(["git", *args], cwd=repo, capture_output=True, text=True,
                          check=False).stdout.strip()


def generate_pr_description(task_id: str, issue_text: str, diff: str, verified: bool) -> str:
    n_changed = sum(1 for ln in diff.splitlines()
                    if ln[:1] in "+-" and not ln.startswith(("+++", "---")))
    status = "✅ verified in sandbox (hidden tests pass)" if verified \
        else "⚠️ NOT verified — do not merge"
    return (f"## Draft fix: {task_id}\n\n**Issue:** {issue_text}\n\n"
            f"**Verification:** {status}\n**Diff size:** {n_changed} changed lines\n\n"
            f"_Generated by ACP guarded execution (draft_pr). Requires human approval before "
            f"apply/merge to a protected branch._")


def build_draft_pr(repo: Path, *, task_id: str, issue_text: str, module_path: str,
                   patch_content: str, verified: bool, base_branch: str = "master") -> DraftPR:
    """Apply a VERIFIED draft to a fresh feature branch + build a PR description + rollback.

    Never commits to a protected branch. If the draft is unverified, the apply is blocked.
    """
    base_commit = _git(repo, "rev-parse", "HEAD")
    branch = safe_branch_name(task_id)
    if branch.split("/")[-1] in PROTECTED_BRANCHES or base_branch != base_branch.strip():
        return DraftPR(task_id=task_id, branch=branch, applied_to_branch=False,
                       targeted_protected_branch=True, verified=verified,
                       base_commit=base_commit, head_commit=None, description="",
                       blocked_reason="refused: target resolves to a protected branch")
    if not verified:
        return DraftPR(task_id=task_id, branch=branch, applied_to_branch=False,
                       targeted_protected_branch=False, verified=False,
                       base_commit=base_commit, head_commit=None,
                       description=generate_pr_description(task_id, issue_text, "", False),
                       blocked_reason="draft not verified in sandbox -> apply blocked")
    # apply on a fresh feature branch (the source/protected branch is never touched)
    _git(repo, "checkout", "-b", branch)
    (repo / module_path).write_text(patch_content)
    _git(repo, "add", "-A")
    _git(repo, "commit", "-m", f"ACP draft fix: {task_id}")
    head = _git(repo, "rev-parse", "HEAD")
    diff = _git(repo, "diff", f"{base_commit}..{head}")
    rollback = RollbackPlan(
        branch=branch, base_commit=base_commit,
        delete_branch_cmd=f"git branch -D {branch}",
        reset_cmd=f"git checkout {base_branch} && git reset --hard {base_commit}")
    # confirm the protected branch's commit is unchanged (we only moved on the feature branch)
    base_head_now = _git(repo, "rev-parse", base_branch)
    return DraftPR(
        task_id=task_id, branch=branch, applied_to_branch=head != base_commit,
        targeted_protected_branch=(base_head_now != base_commit),
        verified=verified, base_commit=base_commit, head_commit=head,
        description=generate_pr_description(task_id, issue_text, diff, verified),
        rollback=rollback.to_dict())


@dataclass
class GuardedPRReport:
    n_tasks: int = 0
    n_draft_prs: int = 0
    n_blocked_unverified: int = 0
    rows: list = field(default_factory=list)

    def to_dict(self) -> dict:
        return {"experiment": "guarded_pr", "n_tasks": self.n_tasks,
                "n_draft_prs": self.n_draft_prs,
                "n_blocked_unverified": self.n_blocked_unverified,
                "zero_protected_branch_writes": all(
                    not r["targeted_protected_branch"] for r in self.rows),
                "all_have_rollback": all(r["rollback"] is not None
                                         for r in self.rows if r["applied_to_branch"]),
                "rows": self.rows}
